### ISSUE TITLE
On Windows 2+2 evaluates to error

### ISSUE THREAD

**Issue by sthiers** [will62794/tlaplus_repl#1]
I just tried the REPL on Windows. 
2+2 evaluates to an error.

In function` tlc_eval`, changing from
`lines = raw_out.split("\n")`	
to
`lines = raw_out.split("\r\n")	`

solved my issue.

S.

**Comment by will62794** [comment]
This should be fixed by commit [9c413d](https://github.com/will62794/tlaplus_repl/commit/9c413d74c39a9fe359d0aa06a08ed7e60b0cd4a7). See if the issue persists after this change.

**Comment by sthiers** [comment]
Everything is ok now.
