### ISSUE TITLE
tla.zip no longer exists

### ISSUE THREAD

**Issue by lemmy** [will62794/tlaplus_repl#2]
https://github.com/will62794/tlaplus_repl/blob/4d2c6acf731e7b209918ee3a5e9d31766d3cf54e/setup_tlc.sh#L16

Should now be https://tla.msr-inria.inria.fr/tlatoolbox/dist/tla2tools.jar (unzip no longer necessary).

**Comment by will62794** [comment]
Should be fixed by [4928e2](https://github.com/will62794/tlaplus_repl/commit/4928e261b9e9f6f7ea44286913e4ead39ef1e651).
